org: devingen
app: khanguru
service: atama-api

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  environment:
    MONGO_ADDRESS: ${param:MONGO_ADDRESS}
    MONGO_USERNAME: ${param:MONGO_USERNAME}
    MONGO_PASSWORD: ${param:MONGO_PASSWORD}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:

  get-all-pairs:
    handler: bin/get-all-pairs
    events:
      - http:
          path: /{base}/{space-id}/all-pairs
          method: get
          cors: true
          request:
            parameters:
              paths:
                base: true
                space-id: true

  get-pairs:
    handler: bin/get-pairs
    events:
      - http:
          path: /{base}/{space-id}/pairs
          method: get
          cors: true
          request:
            parameters:
              paths:
                base: true
                space-id: true

  get-meeting-structure:
    handler: bin/get-meeting-structure
    events:
      - http:
          path: /{base}/{space-id}/meeting-structure
          method: get
          cors: true
          request:
            parameters:
              paths:
                base: true
                space-id: true

  get-meetings:
    handler: bin/get-meetings
    events:
      - http:
          path: /{base}/{space-id}/meetings
          method: get
          cors: true
          request:
            parameters:
              paths:
                base: true
                space-id: true
